 'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
type Module={title:string;status:string;progress:number;completedAt:string|null;links:{label:string;url:string}[]};
type Report={schemaVersion:1;generatedAt:string;lastUpdated:string|null;summary:{learningTracks:number;modulesCompleted:number;exercisesCompleted:number;evidenceItems:number;projects:number;activeModules:number};learningTracks:{title:string;horizon:string;page:number;modules:Module[]}[];timeline:{title:string;date:string;kind:string}[];focusAreas:{name:string;domain:string;completedModules:number;totalModules:number}[];projects:{title:string;links:{label:string;url:string}[]}[];evidence:{title:string;links:{label:string;url:string}[]}[]};
const horizons:Record<string,string>={week:'Week',kort:'Maand',mid:'Kwartaal',lang:'Semester'};
function safe(url:string){try{return ['https:','http:'].includes(new URL(url).protocol)}catch{return false}}
export function LearnTrajectoryPublic({compact=false,embedded=false}:{compact?:boolean;embedded?:boolean}){
 const [data,setData]=useState<Report|null>(null),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[query,setQuery]=useState(''),[days,setDays]=useState(0);
 useEffect(()=>{const c=new AbortController();fetch('/api/leertraject',{signal:c.signal,cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error('Leertraject is tijdelijk niet beschikbaar.');setData(await r.json());setLoaded(true)}).catch(e=>{if(e.name!=='AbortError'){setError(e.message);setLoaded(true)}});return()=>c.abort()},[]);
 return <section className="space-y-8 text-zinc-300" aria-label="Openbaar Leertraject">
 {!embedded&&<header><h2 className="font-display text-2xl text-white">Leertraject</h2><p className="mt-2 text-zinc-400">Gepubliceerde voortgang uit Skillmax.</p></header>}
 {!loaded?<p role="status">Voortgang laden…</p>:error?<p role="status">{error}</p>:!data||!data.lastUpdated?<p className="text-center text-zinc-400">Er zijn nog geen resultaten gepubliceerd.</p>:<>
 <div className="grid grid-cols-2 gap-4 md:grid-cols-3">{[[data.summary.learningTracks,'Leertrajecten'],[data.summary.modulesCompleted,'Afgeronde onderdelen'],[data.summary.exercisesCompleted,'Geslaagde pogingen'],[data.summary.activeModules,'Actieve onderdelen'],[data.summary.projects,'Projecten'],[data.summary.evidenceItems,'Bewijsitems']].slice(0,compact?3:6).map(([n,label])=><div key={label} className="rounded-2xl border border-white/10 bg-white/[.02] p-5"><strong className="block font-display text-3xl text-white">{n}</strong><span className="text-sm text-zinc-400">{label}</span></div>)}</div>
 {!compact&&<div className="flex flex-wrap gap-4"><label className="flex-1">Zoek leertraject<input className="mt-2 w-full rounded-xl border border-white/15 bg-zinc-900 p-3" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Tijdlijn<select className="mt-2 block rounded-xl border border-white/15 bg-zinc-900 p-3" value={days} onChange={e=>setDays(Number(e.target.value))}><option value={0}>Alle tijd</option><option value={7}>7 dagen</option><option value={30}>30 dagen</option><option value={90}>90 dagen</option></select></label></div>}
 {!compact&&<div className="grid gap-5 md:grid-cols-2">{data.learningTracks.filter(t=>t.title.toLowerCase().includes(query.toLowerCase())).map((t,i)=><article className="rounded-2xl border border-white/10 p-6" key={i}><p className="text-sm text-zinc-500">{horizons[t.horizon]} {t.page}</p><h3 className="font-display text-xl text-white">{t.title}</h3>{t.modules.map((m,j)=><div className="mt-5" key={j}><p>{m.title}</p><div className="flex items-center gap-3"><progress className="w-full accent-white" max={100} value={m.progress}/><span>{m.progress}%</span></div><p className="text-sm text-zinc-500">{m.status}</p>{m.links.filter(l=>safe(l.url)).map((l,k)=><a className="mr-4 text-sm underline" key={k} href={l.url} target="_blank" rel="noopener noreferrer">{l.label} ↗</a>)}</div>)}</article>)}</div>}
 <section><h3 className="mb-4 font-display text-xl text-white">Tijdlijn</h3>{data.timeline.filter(t=>(!days||Date.parse(t.date)>=Date.now()-days*86400000)&&t.title.toLowerCase().includes(query.toLowerCase())).slice(0,compact?3:100).map((t,i)=><p className="my-3 border-l border-white/20 pl-4" key={i}><time className="mr-4 text-zinc-500">{new Date(t.date).toLocaleDateString('nl-NL')}</time>{t.title}</p>)}</section>
 {!compact&&data.focusAreas.length>0&&<section><h3 className="mb-4 font-display text-xl text-white">Ontwikkeling per domein</h3><table className="w-full text-left"><thead><tr><th>Skill</th><th>Domein</th><th>Afgeronde onderdelen</th></tr></thead><tbody>{data.focusAreas.map((f,i)=><tr key={i}><td className="py-3">{f.name}</td><td>{f.domain}</td><td>{f.completedModules}/{f.totalModules}</td></tr>)}</tbody></table></section>}
 {!compact&&[...data.projects,...data.evidence].length>0&&<section><h3 className="font-display text-xl text-white">Projecten & bewijs</h3>{[...data.projects,...data.evidence].map((r,i)=><p className="my-3" key={i}>{r.title} {r.links.filter(l=>safe(l.url)).map((l,j)=><a className="ml-3 underline" key={j} href={l.url} target="_blank" rel="noopener noreferrer">{l.label} ↗</a>)}</p>)}</section>}
 <p className="text-xs text-zinc-500">Bijgewerkt: {new Date(data.lastUpdated).toLocaleString('nl-NL')}</p></>}
 {compact&&<Link className="inline-block rounded-xl border border-white/20 px-4 py-2" href="/learning-trajectory">Volledig Leertraject bekijken ↗</Link>}
 </section>;
}
