'use client';
import {useMemo,useState} from 'react';
import Image from 'next/image';
import type {EvidenceRecord,Series} from '@/lib/learning-radar';
import {aggregateTechnologies,bubbleDiameter,type TechnologyNode} from '@/lib/technology-evidence';
import {techIcons} from '@/data/tech-stack';
import './tech-evidence.css';
const keys:Series[]=['theory','practice','exercises'];
const colors=['#b69af5','#5b91f5','#59d6ca'];
const groups:Record<string,string>={software:'Web & Software',ai:'AI & LLM',cloud:'Cloud & Backend',automation:'Automation',integration:'Integration',data:'Data',security:'Security',delivery:'DevOps / Delivery',other:'Other'};
export default function TechEvidence({records,lang}:{records:EvidenceRecord[];lang:'NL'|'EN'|'DE'}){
 const nodes=useMemo(()=>aggregateTechnologies(records),[records]);
 const [selected,setSelected]=useState<string|null>(null),[hover,setHover]=useState<string|null>(null),[query,setQuery]=useState(''),[group,setGroup]=useState('all');
 const nl=lang==='NL',de=lang==='DE';const series=nl?['Theorie','Praktijk','Oefenen']:de?['Theorie','Praxis','Übungen']:['Theory','Practice','Exercises'];
 const available=[...new Set(nodes.map(n=>n.group))];
 const filtered=nodes.filter(n=>(group==='all'||n.group===group)&&n.name.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 const active=nodes.find(n=>n.id===selected)||filtered[0];const preview=nodes.find(n=>n.id===hover);
 const evidence=active?records.filter(e=>active.evidenceIds.includes(e.id)):[];
 const counts=(node:TechnologyNode)=><div className="tech-counts">{keys.map((key,i)=><span key={key}><i style={{background:colors[i]}}/>{series[i]} <b>{node.counts[key]}</b></span>)}</div>;
 const ring=(node:TechnologyNode)=>{let angle=0;return 'conic-gradient('+keys.map((key,i)=>{const start=angle;angle+=node.counts[key]/node.strength*100;return `${colors[i]} ${start}% ${angle}%`}).join(',')+')'};
 return <div className="tech-view">
  <div className="tech-toolbar"><label><span className="sr-only">{nl?'Zoek technologie':de?'Technologie suchen':'Search technology'}</span><input type="search" value={query} onChange={e=>{setQuery(e.target.value);setSelected(null);setHover(null)}} placeholder={nl?'Zoek technologie…':de?'Technologie suchen…':'Search technology…'}/></label><select aria-label={nl?'Technologiegroep':'Technology group'} value={group} onChange={e=>{setGroup(e.target.value);setSelected(null);setHover(null)}}><option value="all">{nl?'Alle groepen':de?'Alle Gruppen':'All groups'}</option>{available.map(g=><option key={g} value={g}>{groups[g]||g}</option>)}</select><small>{filtered.length} {nl?'technologieën':de?'Technologien':'technologies'}</small></div>
  <div className="tech-layout"><div className="tech-map" aria-label="Tech Stack"><div className="tech-hover" aria-live="polite">{preview?<><strong>{preview.name}</strong>{counts(preview)}<small>{preview.strength} evidence records · {preview.moduleIds.length} {nl?'modules':de?'Module':'modules'}</small></>:<span>{nl?'Selecteer een technologie om de bronnen te bekijken.':de?'Technologie auswählen, um Quellen zu sehen.':'Select a technology to explore its evidence.'}</span>}</div>
   {available.filter(g=>filtered.some(n=>n.group===g)).map(g=><section className="tech-cluster" key={g}><h4>{groups[g]||g}</h4><div className="tech-bubbles">{filtered.filter(n=>n.group===g).map(node=><button key={node.id} type="button" className="tech-node" aria-pressed={active?.id===node.id} aria-label={`${node.name}: ${keys.map((k,i)=>`${series[i]} ${node.counts[k]}`).join(', ')}`} onMouseEnter={()=>setHover(node.id)} onMouseLeave={()=>setHover(null)} onFocus={()=>setHover(node.id)} onBlur={()=>setHover(null)} onClick={()=>{setSelected(node.id);setHover(node.id);if(window.matchMedia('(max-width:900px)').matches)document.getElementById('tech-evidence-details')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth',block:'start'})}}><span className="tech-orbit" style={{width:bubbleDiameter(node.strength),height:bubbleDiameter(node.strength),background:ring(node)}}><span className="tech-core">{techIcons[node.name]?<Image src={techIcons[node.name]} alt="" width={26} height={26} unoptimized/>:<span className="tech-initial" aria-hidden="true">{node.name.slice(0,2)}</span>}<b>{node.strength}</b></span></span><span className="tech-name">{node.name}</span></button>)}</div></section>)}{!filtered.length&&<p>{nl?'Geen technologieën gevonden.':de?'Keine Technologien gefunden.':'No technologies found.'}</p>}
  </div><aside id="tech-evidence-details" className="tech-inspector" aria-label={nl?'Technologie-evidence':'Technology evidence'}>{active?<><p className="tech-kicker">TECH STACK / {groups[active.group]}</p><h3>{active.name}</h3>{counts(active)}<p className="tech-meta">{active.strength} evidence records · {active.moduleIds.length} {nl?'gekoppelde modules':de?'verknüpfte Module':'linked modules'}</p>{active.versions.length>0&&<p>{nl?'Versies':'Versions'}: {active.versions.join(', ')}</p>}<div className="tech-sources">{keys.map((key,i)=>evidence.some(e=>e.series===key)&&<section key={key}><h4 style={{color:colors[i]}}>{series[i]}</h4>{evidence.filter(e=>e.series===key).map(e=><article key={e.id}><a href={e.url}>{e.title} ↗</a>{e.date&&<small>{e.dateKind==='completed'?(nl?'Behaald':de?'Abgeschlossen':'Completed'):(nl?'Gedocumenteerd':de?'Dokumentiert':'Documented')}: {e.date.split('-').reverse().join('/')}</small>}{e.issuer&&<small>{e.issuer}</small>}<details><summary>{nl?'Brononderbouwing':de?'Quellendetails':'Source details'}</summary><p>{e.detail}</p>{e.credential&&<a href={e.credential}>{nl?'Certificaat':'Certificate'} ↗</a>}{e.technologies.filter(m=>m.name===active.name&&m.moduleId).map(m=><p key={m.moduleId}><a href={m.url}>{m.moduleTitle} ↗</a></p>)}</details></article>)}</section>)}</div></>:<p>{nl?'Geen technologie-evidence beschikbaar.':'No technology evidence available.'}</p>}</aside></div>
  <p className="tech-method">{nl?'Grootte = unieke projecten, cursussen en gelogde oefeningen. Modules onderbouwen hun cursus; commits en deployments vergroten de bolletjes niet.':'Size = unique projects, courses and logged exercises. Modules support their course; commits and deployments do not increase bubble size.'}</p>
 </div>;
}
